1. Huggingface Hub(Finetuning chapter will discuss this HF in detail)
2. OpenAI SDK(Lang-chain)
2. Gemini SDK(Lang-chain)

HF
Langchain

In [44]:
from dotenv import load_dotenv
import os

load_dotenv(override=True)

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
HF_API_KEY = os.getenv("HF_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

In [45]:
print(bool(GOOGLE_API_KEY))
print(bool(HF_API_KEY))
print(bool(OPENAI_API_KEY))

True
True
True


In [37]:
from sentence_transformers import SentenceTransformer

In [5]:
open_source_embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

/home/abhishek/GitHub_Projects/Full-Stack-GenAI-Bootcamp-1.0/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:180: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 12020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:119.)
  return torch._C._cuda_getDeviceCount() > 0


In [6]:
text = "machine"

In [7]:
embedding =open_source_embedding_model.encode(text)

In [8]:
embedding

array([-7.21354261e-02,  2.84874532e-02, -1.17706209e-02,  1.98008865e-02,
       -4.34783213e-02, -3.14590745e-02,  1.49604967e-02,  2.88980245e-03,
        3.24486336e-03, -3.39518711e-02,  1.04991822e-02, -1.02072181e-02,
        7.77680725e-02, -7.65563697e-02, -1.39956619e-03, -2.10196991e-03,
        1.71923507e-02, -6.33647814e-02, -2.81336978e-02, -5.86969294e-02,
       -3.29725482e-02,  1.02291554e-02, -6.45695031e-02,  1.98799856e-02,
       -1.06031308e-02,  1.04793452e-01, -3.81070748e-02,  5.03517799e-02,
        2.06003264e-02, -1.30085528e-01, -2.18260754e-02,  4.07634676e-03,
        6.23282176e-05,  2.95541044e-02,  3.27022374e-02, -1.54474853e-02,
        3.09898760e-02, -3.76024991e-02,  1.37064438e-02, -5.00647239e-02,
        2.30320450e-02, -7.93178380e-02, -8.26061932e-06, -1.97606795e-02,
        7.49427900e-02,  1.02477841e-01,  6.01522485e-03, -3.98588628e-02,
        5.47022447e-02,  3.11047845e-02, -1.16405964e-01, -7.04231113e-02,
        6.45304099e-02,  

In [9]:
len(embedding)

384

In [10]:
embedding.shape

(384,)

In [11]:
sentence = "How to reduce heart disease risk?"

In [12]:
embedding =open_source_embedding_model.encode(sentence)

In [13]:
embedding.shape

(384,)

In [14]:
paragraph = """
Machine learning is a field of artificial intelligence that focuses on building systems 
that learn from data. It is widely used in applications like recommendation systems, 
image recognition, and natural language processing.
"""

In [15]:
embedding = open_source_embedding_model.encode(paragraph)

In [16]:
embedding.shape

(384,)

In [17]:
embedding

array([-2.78186686e-02, -6.40662573e-03,  3.68497521e-02,  2.21399567e-03,
        2.55084615e-02,  1.34022748e-02,  6.45560585e-03, -3.05501129e-02,
       -6.01915941e-02, -2.28518434e-02, -7.05490857e-02,  1.97643526e-02,
        5.54116294e-02, -3.38736363e-02, -9.74513777e-03,  4.72750328e-02,
       -1.58115588e-02, -1.64723694e-02, -6.00375645e-02, -7.00235814e-02,
        2.54246537e-02, -5.45068271e-03, -7.51983151e-02,  1.57804247e-02,
       -1.62698682e-02,  5.30246720e-02,  6.29330277e-02,  1.47748711e-02,
       -1.32338861e-02,  5.44604147e-03,  2.14249045e-02, -3.44793051e-02,
        1.16899833e-02,  4.35766988e-02, -4.42826189e-02,  5.05335964e-02,
       -2.66971439e-02,  5.36214188e-03,  7.96872284e-03, -1.89669970e-02,
       -6.25874922e-02, -7.47380778e-02,  6.55540079e-03, -6.77178148e-03,
        1.26145616e-01,  1.28760278e-01, -7.31318966e-02, -9.79881361e-02,
        8.16423330e-04,  1.73747428e-02, -1.05541281e-01,  1.18358284e-02,
       -1.23240687e-02,  

In [18]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings

In [31]:
google_embeddings_model = GoogleGenerativeAIEmbeddings(model="gemini-embedding-001")

In [32]:
embedding = google_embeddings_model.embed_query("What is the capital of France?")

In [33]:
len(embedding)

3072

In [41]:
from langchain_openai import OpenAIEmbeddings

In [46]:
openai_embeddings_model=OpenAIEmbeddings(
    model="text-embedding-3-large",
    api_key=OPENAI_API_KEY
)

In [47]:
embedding = openai_embeddings_model.embed_query("What is the capital of France?")

In [48]:
len(embedding)

3072

In [52]:
openai_embeddings_small_model=OpenAIEmbeddings(
    model="text-embedding-3-small",
    api_key=OPENAI_API_KEY
)

In [53]:
embedding = openai_embeddings_small_model.embed_query("What is the capital of France?")

In [54]:
len(embedding)

1536

TEXT

IMAGE?

ViT(vision transformer) and CLIP(contrastive language-image pretraining) are two popular transformer-based models used for image processing tasks.

In [55]:
from transformers import CLIPModel, CLIPProcessor

In [56]:
from PIL import Image

In [57]:
path = r"/home/abhishek/GitHub_Projects/Full-Stack-GenAI-Bootcamp-1.0/Class-08-18-Apr-SOTA-Transformer-Embedding-Methods/image/flower.jpg"

In [58]:
image = Image.open(path)

In [59]:
image.show()

In [39]:
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.


In [38]:
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")

In [41]:
inputs =processor(images=image, return_tensors="pt")

In [44]:
import torch

In [45]:
# Get embedding
with torch.no_grad():
    image_embedding = model.get_image_features(**inputs)

In [46]:
image_embedding

tensor([[ 3.0268e-01,  4.7514e-02, -1.0944e-01,  3.7604e-01, -3.3138e-01,
          1.0324e-01, -4.7890e-02,  3.5617e-01,  7.6529e-01,  5.0290e-02,
          4.5722e-01, -2.6173e-01,  3.0070e-02, -6.6185e-01, -1.8770e-01,
         -1.2801e-02,  1.8427e+00,  2.3160e-02,  8.1963e-02, -4.2190e-01,
          1.7335e+00,  1.3869e-01, -1.2739e-01, -3.0044e-01,  1.2033e-01,
          1.4199e-01, -9.9706e-04,  2.3606e-01,  2.7052e-01,  5.5268e-02,
         -3.1191e-02, -2.4044e-01, -1.8626e-01,  2.3131e-01,  2.8196e-01,
          2.7599e-01, -6.9388e-02,  1.7465e-01, -2.6055e-01, -1.2248e+00,
         -8.6463e-01, -3.5701e-02,  8.5625e-01, -4.4047e-01, -1.6610e-01,
          3.4468e+00,  1.6835e-01,  1.6050e-01,  8.8021e-02,  6.7718e-01,
         -3.8039e-01,  3.9413e-01,  5.1323e-01, -2.6127e-02, -3.4481e-01,
          7.0976e-01, -1.6183e-01,  6.1377e-02,  3.0291e-01, -1.6714e-01,
          4.8288e-01, -2.3115e-01,  1.4020e-01,  7.4183e-02, -2.1236e-01,
         -4.6074e-01, -2.6213e-01,  9.

In [48]:
len(image_embedding[0])

512